# Generated by Django 5.2.5 on 2025-08-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=50, null=True)),
                ('Date', models.DateField(default=0)),
                ('Mood', models.CharField(max_length=50, null=True)),
                ('StressLevel', models.BooleanField(default=0)),
                ('SleepHours', models.IntegerField(default=0)),
                ('Appetite', models.CharField(max_length=50, null=True)),
                ('EnergyLevel', models.CharField(max_length=50, null=True)),
                ('MedicationTaken', models.BooleanField(max_length=50, null=True)),
                ('TherapyExercise', models.CharField(max_length=50, null=True)),
                ('DailyGoalAchieved', models.BooleanField(null=True)),
                ('Remarks', models.TextField(null=True)),
            ],
        ),
    ]
