# Generated by Django 5.2.5 on 2025-08-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoodTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_db',
            name='StressLevel',
            field=models.IntegerField(default=0),
        ),
    ]
