# Generated by Django 5.2.5 on 2025-08-28 03:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoodTracker', '0002_alter_information_db_stresslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_db',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='information_db',
            name='MedicationTaken',
            field=models.BooleanField(null=True),
        ),
    ]
