# Generated by Django 5.2.5 on 2025-08-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoodTracker', '0003_alter_information_db_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=3, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('chronic_diseases', models.TextField(blank=True, null=True)),
                ('previous_surgeries', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
