# Generated by Django 5.2.5 on 2025-08-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoodTracker', '0004_patient_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_db',
            name='DailyGoalAchieved',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='information_db',
            name='MedicationTaken',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
