# Generated by Django 5.2.5 on 2025-08-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0003_alter_user_aadhaar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
