# Generated by Django 5.2.5 on 2025-08-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0004_alter_user_aadhaar_number_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhaar_number',
            field=models.IntegerField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
