# Generated by Django 5.2.5 on 2025-08-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0005_alter_user_aadhaar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhaar_number',
            field=models.IntegerField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.BigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
