# Generated by Django 5.2.5 on 2025-08-29 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0006_alter_user_aadhaar_number_alter_user_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhaar_number',
        ),
    ]
