# Generated by Django 5.2.5 on 2025-08-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0007_remove_user_aadhaar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
